(in-package :ethif)

;;; SOCK_xxx
(defconstant +SOCK_STREAM+ 1 "Sequenced, reliable, connection-based byte streams")
(defconstant +SOCK_DGRAM+ 2 "Connectionless, unreliable datagrams of fixed maximum length")
(defconstant +SOCK_RAW+ 3 "Raw protocol interface")
(defconstant +SOCK_RDM+ 4 "Reliably-delivered messages")
(defconstant +SOCK_SEQPACKET+ 5 "Sequenced, reliable, connection-based, datagrams of fixed maximum length")
(defconstant +SOCK_DCCP+ 6 "Datagram Congestion Control Protocol")
(defconstant +SOCK_PACKET+ 10 "Linux specific way of getting packets at the dev level. For writing rarp and other similar things on the user level")


;;; IFxxx
(defconstant +IFNAMSIZ+ 16 "TODO")
(defconstant +IFHWADDRLE+ 6 "TODO")


;;; Address families
(defconstant +AF_UNSPEC+ 0 "Unspecified")
(defconstant +AF_LOCAL+ 1 "Local to host (pipes and file-domain)")
(defconstant +AF_UNIX+ +AF_LOCAL+ "POSIX name for AF_LOCAL")
(defconstant +AF_FILE+ +AF_LOCAL+ "Another non-standard name for AF_LOCAL")
(defconstant +AF_INET+ 2 "IP protocol family")
(defconstant +AF_AX25+ 3 "Amateur Radio AX.25")
(defconstant +AF_IPX+ 4 "Novell Internet Protocol")
(defconstant +AF_APPLETALK+ 5 "Appletalk DDP")
(defconstant +AF_NETROM+ 6 "Amateur radio NetROM")
(defconstant +AF_BRIDGE+ 7 "Multiprotocol bridge")
(defconstant +AF_ATMPVC+ 8 "ATM PVCs")
(defconstant +AF_X25+ 9 "Reserved for X.25 project")
(defconstant +AF_INET6+ 10 "IP Version 6")
(defconstant +AF_ROSE+ 11 "Amateur Radio X.25 PLP")
(defconstant +AF_DECnet+ 12 "Reserved for DECnet project")
(defconstant +AF_NETBEUI+ 13 "Reserved for 802.2LLC project")
(defconstant +AF_SECURITY+ 14 "Security callback pseudo AF")
(defconstant +AF_KEY+ 15 "PF KEY key management API")
(defconstant +AF_NETLINK+ 16 "TODO")
(defconstant +AF_ROUTE+ +AF_NETLINK+ "Alias to emulate 4.4BSD")
(defconstant +AF_PACKET+ 17 "acket family")
(defconstant +AF_ASH+ 18 "Ash")
(defconstant +AF_ECONET+ 19 "Acorn Econet")
(defconstant +AF_ATMSVC+ 20 "ATM SVCs")
(defconstant +AF_RDS+ 21 "RDS sockets")
(defconstant +AF_SNA+ 22 "Linux SNA Project")
(defconstant +AF_IRDA+ 23 "IRDA sockets")
(defconstant +AF_PPPOX+ 24 "PPPoX sockets")
(defconstant +AF_WANPIPE+ 25 "Wanpipe API sockets")
(defconstant +AF_LLC+ 26 "Linux LLC")
(defconstant +AF_CAN+ 29 "Controller Area Network")
(defconstant +AF_TIPC+ 30 "TIPC sockets")
(defconstant +AF_BLUETOOTH+ 31 "Bluetooth sockets")
(defconstant +AF_IUCV+ 32 "IUCV sockets")
(defconstant +AF_RXRPC+ 33 "RxRPC sockets")
(defconstant +AF_ISDN+ 34 "mISDN sockets")
(defconstant +AF_PHONET+ 35 "Phonet sockets")
(defconstant +AF_IEEE802154+ 36 "IEEE 802.16.4 sockets")
(defconstant +AF_MAX+ 47 "For now")


;;; SIOCxxx
(defconstant +SIOCINQ+ #x541B "TODO")
(defconstant +SIOCOUTQ+ #x5411 "TODO")
(defconstant +SIOCADDRT #x890B "add routing table entry")
(defconstant +SIOCADDRT+ #x890B "add routing table entry")
(defconstant +SIOCDELRT+ #x890C "delete routing table entry")
(defconstant +SIOCRTMSG+ #x890D	"call to routing system")
(defconstant +SIOCGIFNAME+ #x8910 "get iface name")
(defconstant +SIOCSIFLINK+ #x8911 "set iface channel")
(defconstant +SIOCGIFCONF+ #x8912 "get iface list")
(defconstant +SIOCGIFFLAGS+ #x8913 "get flags")
(defconstant +SIOCSIFFLAGS+ #x8914 "set flags")
(defconstant +SIOCGIFADDR+ #x8915 "get PA address")
(defconstant +SIOCSIFADDR+ #x8916 "set PA address")
(defconstant +SIOCGIFDSTADDR+ #x8917 "get remote PA address")
(defconstant +SIOCSIFDSTADDR+ #x8918 "set remote PA address")
(defconstant +SIOCGIFBRDADDR+ #x8919 "get broadcast PA address")
(defconstant +SIOCSIFBRDADDR+ #x891a "set broadcast PA address")
(defconstant +SIOCGIFNETMASK+ #x891b "get network PA mask")
(defconstant +SIOCSIFNETMASK+ #x891c "set network PA mask")
(defconstant +SIOCGIFMETRIC+ #x891d "get metric")
(defconstant +SIOCSIFMETRIC+ #x891e "set metric")
(defconstant +SIOCGIFMEM+ #x891f "get memory address (BSD)")
(defconstant +SIOCSIFMEM+ #x8920 "set memory address (BSD)")
(defconstant +SIOCGIFMTU+ #x8921 "get MTU size")
(defconstant +SIOCSIFMTU+ #x8922 "set MTU size")
(defconstant +SIOCSIFNAME+ #x8923 "set interface name")
(defconstant +SIOCSIFHWADDR+ #x8924 "set hardware address")
(defconstant +SIOCGIFENCAP+ #x8925 "get/set encapsulations")
(defconstant +SIOCSIFENCAP+ #x8926 "TODO")
(defconstant +SIOCGIFHWADDR+ #x8927 "Get hardware address")
(defconstant +SIOCGIFSLAVE+ #x8929 "Driver slaving support")
(defconstant +SIOCSIFSLAVE+ #x8930 "TODO")
(defconstant +SIOCADDMULTI+ #x8931 "Multicast address lists")
(defconstant +SIOCDELMULTI+ #x8932)
(defconstant +SIOCGIFINDEX+ #x8933 "name -> if_index mapping")
(defconstant +SIOGIFINDEX+ +SIOCGIFINDEX+ "misprint compatibility :-)")
(defconstant +SIOCSIFPFLAGS+ #x8934 "set/get extended flags set")
(defconstant +SIOCGIFPFLAGS+ #x8935 "TODO")
(defconstant +SIOCDIFADDR+ #x8936 "delete PA address")
(defconstant +SIOCSIFHWBROADCAST+ #x8937 "set hardware broadcast addr")
(defconstant +SIOCGIFCOUNT+ #x8938 "get number of devices")
(defconstant +SIOCGIFBR+ #x8940 "Bridging support")
(defconstant +SIOCSIFBR+ #x8941 "Set bridging options")
(defconstant +SIOCGIFTXQLEN+ #x8942 "Get the tx queue length")
(defconstant +SIOCSIFTXQLEN+ #x8943 "Set the tx queue length")
(defconstant +SIOCGIFDIVERT+ #x8944 "Frame diversion support")
(defconstant +SIOCSIFDIVERT+ #x8945 "Set frame diversion options")
(defconstant +SIOCETHTOOL+ #x8946 "Ethtool interface")
(defconstant +SIOCGMIIPHY+ #x8947 "Get address of MII PHY in use")
(defconstant +SIOCGMIIREG+ #x8948 "Read MII PHY register")
(defconstant +SIOCSMIIREG+ #x8949 "Write MII PHY register")
(defconstant +SIOCWANDEV+  #x894A "get/set netdev parameters")
(defconstant +SIOCDARP+	#x8953 "delete ARP table entry")
(defconstant +SIOCGARP+	#x8954 "get ARP table entry")
(defconstant +SIOCSARP+	#x8955 "set ARP table entry")
(defconstant +SIOCDRARP+ #x8960 "delete RARP table entry")
(defconstant +SIOCGRARP+ #x8961 "get RARP table entry")
(defconstant +SIOCSRARP+ #x8962 "set RARP table entry")
(defconstant +SIOCGIFMAP+ #x8970 "Get device parameters")
(defconstant +SIOCSIFMAP+ #x8971 "Set device parameters")
(defconstant +SIOCADDDLCI+ #x8980 "Create new DLCI device")
(defconstant +SIOCDELDLCI+ #x8981 "Delete DLCI device")
(defconstant +SIOCGIFVLAN+ #x8982 "802.1Q VLAN support")
(defconstant +SIOCSIFVLAN+ #x8983 "Set 802.1Q VLAN options")
(defconstant +SIOCBONDENSLAVE+ #x8990 "enslave a device to the bond")
(defconstant +SIOCBONDRELEASE+ #x8991 "release a slave from the bond")
(defconstant +SIOCBONDSETHWADDR+ #x8992 "set the hw addr of the bond")
(defconstant +SIOCBONDSLAVEINFOQUERY+ #x8993 "rtn info about slave state")
(defconstant +SIOCBONDINFOQUERY+ #x8994 "rtn info about bond state")
(defconstant +SIOCBONDCHANGEACTIVE+ #x8995 "update to a new active slave")
(defconstant +SIOCBRADDBR+ #x89a0 "create new bridge device")
(defconstant +SIOCBRDELBR+ #x89a1 "remove bridge device")
(defconstant +SIOCBRADDIF+ #x89a2 "add interface to bridge")
(defconstant +SIOCBRDELIF+ #x89a3 "remove interface from bridge")
(defconstant +SIOCSHWTSTAMP+ #x89b0 "TODO")
(defconstant +SIOCDEVPRIVATE+ #x89F0 "to 89FF")
(defconstant +SIOCPROTOPRIVATE+ #x89E0 "to 89EF")
